# Generated by Django 3.2.4 on 2021-06-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20210630_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='table',
            name='_type',
            field=models.CharField(blank=True, choices=[('物理机', '物理机'), ('虚拟机', '虚拟机'), ('交换机', '交换机'), ('防火墙', '防火墙'), ('存储设备', '存储设备')], max_length=16, null=True, verbose_name='资产类别'),
        ),
        migrations.AlterField(
            model_name='table',
            name='new_asset_number',
            field=models.CharField(default='x', max_length=16, unique=True, verbose_name='新资产编号'),
        ),
    ]
