# Generated by Django 3.2.4 on 2021-06-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20210630_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='new_asset_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='新资产编号'),
        ),
    ]
