# Generated by Django 3.2.4 on 2021-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_alter_table_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'permissions': (('can_view_password', 'Can view password'), ('approver', 'approver')), 'verbose_name_plural': '资产表'},
        ),
        migrations.AddField(
            model_name='table',
            name='stauts',
            field=models.CharField(default='库存', max_length=16, verbose_name='状态'),
        ),
    ]
