# Generated by Django 3.2.4 on 2021-07-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_auto_20210701_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='new_asset_number',
            field=models.CharField(blank=True, default='', max_length=16, null=True, unique=True, verbose_name='新资产编号'),
        ),
    ]
